site_name: Oceançš„ç¬”è®°

theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex  
  - pymdownx.betterem  
  - pymdownx.tasklist 
  - admonition
  
nav:
  - "ğŸš© ä»è¿™é‡Œå¼€å§‹":
    - "å°é¢": index.md
  - "ğŸ“” è¯¾å†…ç¬”è®°": 
    - "ğŸ  é¦–é¡µ": course_note/index.md
    - "â™ ï¸ å¤§ä¸€ä¸‹|ç¦»æ•£æ•°å­¦åŠå…¶åº”ç”¨":
      - course_note/D1_DM/Chapter1.md
      - course_note/D1_DM/Chapter2.md
      - course_note/D1_DM/Chapter5.md
    - "â™£ï¸ å¤§ä¸€ä¸‹|æ•°æ®ç»“æ„åŸºç¡€":
      - course_note/D1_DS/Chapter4.md
  - "ğŸ’» ç®—æ³•å­¦ä¹ ":
    - "ğŸ  é¦–é¡µ": algorithm/index.md
    - "åˆ†æ²»ç®—æ³•" : algorithm/divide.md
    - "æœç´¢ä¸å›¾è®º" : algorithm/searchgraph.md
  - "ğŸ§¾ è¯­è¨€å­¦ä¹ ":
    - "ğŸ  é¦–é¡µ": language/index.md
    - "cpp": 
      - language/cpp/read&write.md
      - language/cpp/stl.md
  - "ğŸ”‰ ç¢ç¢å¿µ":
    - others/è½¯ä»¶å®£è®²ä¼šç¬”è®°.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/contrib/auto-render.min.js
  - _js/katex.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/katex.min.css

